config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  get 'top/login'
  get 'top/main'
  get 'top/new'
  get 'top/logout'
  post 'top/create'
  root 'top#main'
  post 'top/login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def L5
        session[:c] ||= 0
        session[:c] = session[:c].to_i + 1
        render plain: session[:c]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid] != nil
            render "main"
        else
            render "login"
        end
    end
    
    def login
        if User.find_by(uid: params[:uid])
            session[:login_uid] = params[:uid]
            redirect_to top_main_path
            
        else
            render "error"
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to top_main_path
    end
    
    def create
        hashed_password = BCrypt::Password.create(params[:pass])
        user = User.new(uid: params[:uid], pass: hashed_password)
        user.save
        redirect_to top_main_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
エラーです

<%= link_to '戻る', :back %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %><br>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag '登録' %><br>
<% end %>

<p><%= link_to '新規登録', top_new_path %></p>

app/views/top/main.html.erb
<h1>ログインされました</h1>
<%= link_to "ログアウト", top_logout_path %>

app/views/top/new.html.erb
<%= form_tag ({ action: :create }) do %>
  <%= label_tag :uid, 'ユーザー名' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag '新規登録' %>
<% end %>